version: "3.9"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=redis:redis
    ports:
      - '7171:8081'
  zookeeper-server:
    image: 'zookeeper:latest'
    ports:
      - '2181:2181'
    networks:
      - my-app-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
    networks:
      - my-app-network
  content-submit-api:
    container_name: content-api
    build:
      context: .
      dockerfile: Dockerfile
    image: nasruddinkhan/content-submit-api:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
      - 8087:8088
    environment:
      WAIT_HOSTS: mymongodb:27017
    depends_on:
      - docker-mymongodb
      - edureka-service
      - zipkin-server
    networks:
      - my-app-network
  edureka-service:
    container_name: edureka-service
    image: nasruddinkhan/edureka-service:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
      - 8761:8761
    depends_on:
      - zipkin-server
    networks:
      - my-app-network
  api-gateway:
    container_name: api-gateway
    image: nasruddinkhan/api-gateway:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
      - 8002:8002
    depends_on:
      - edureka-service
      - zipkin-server
    networks:
      - my-app-network
  zipkin-server:
    container_name: zipkin-server
    image: openzipkin/zipkin
    restart: on-failure
    ports:
      - 9411:9411
    networks:
      - my-app-network
  docker-mymongodb:
    container_name: mymongodb
    environment:
      #- MONGO_INITDB_ROOT_USERNAME=mongodb
      #- MONGO_INITDB_ROOT_PASSWORD=pass12345
      - MONGODB_DATABASE=content-api
    networks:
      - my-app-network
    volumes:
      - mymongodb_container:/data/db
    ports:
      - 27017:27017
    image: mongo:latest
    restart: always
networks:
  my-app-network:
    driver: bridge
volumes:
  mymongodb_container:

