version: "3.9"
services:
  zookeeper-server:
    image: 'zookeeper:latest'
    ports:
      - '2181:2181'
    networks:
      - my-app-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
    networks:
      - my-app-network
  content-submit-api:
    container_name: content-api
    build:
      context: .
      dockerfile: Dockerfile
    image: nasruddinkhan/content-submit-api:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
      - 8087:8088
      - 9087:8088
      - 1087:8088
    environment:
      WAIT_HOSTS: mymongodb:27017
    depends_on:
      - docker-mymongodb
    networks:
      - my-app-network
  docker-mymongodb:
    container_name: mymongodb
    environment:
      #- MONGO_INITDB_ROOT_USERNAME=mongodb
      #- MONGO_INITDB_ROOT_PASSWORD=pass12345
      - MONGODB_DATABASE=content-api
    networks:
      - my-app-network
    volumes:
      - mymongodb_container:/data/db
    ports:
      - 27017:27017
    image: mongo:latest
    restart: always
networks:
  my-app-network:
    driver: bridge
volumes:
  mymongodb_container:

