server:
  port: 8089
spring:
  data:
    mongodb:
      host: localhost
      port:  27017
      database: content-api
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  secretKey: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789~!@#$%^&*()_+=';?><
logging:
  level:
    com.mypractice.content.api: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

springdoc:
  api-docs:
    path: /content-openapi
