server:
  port: 8088
spring:
  data:
    mongodb:
      host: mymongodb
      #host: localhost
      port: 27017
      #port: 27018
      database: content-api
  kafka:
    bootstrap-servers: kafka-server:9092
    producer:
      topic: upload-content-events-v1
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: 1
jwt:
  secretKey: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789~!@#$%^&*()_+=';?><
logging:
  level:
    com.mypractice.content.api: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

springdoc:
  api-docs:
    path: /content-openapi
